version: "3.3"
services:
  neo4j:
    image: neo4j:latest
    environment: 
      - NEO4J_AUTH=neo4j/password
    ports: 
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    expose:
      - 7474
      - 7687